version: "3"
services:
  db:
    image: "bitnami/mongodb:latest"
    ports:
      - '27017:27017'
    environment:
      MONGODB_USERNAME: graphql
      MONGODB_PASSWORD: josh12
      MONGODB_DATABASE: graphqlYoga
    volumes:
      - './containers/mongo:/data/db'